In [1]:
import numpy as np
import pandas as pd
import csv

In [2]:
from sklearn.metrics import roc_curve

In [3]:
ss=[]
lp=[]

for i in ['100']:
    s= pd.read_csv('/home/mvasist/samples/1/'+ i +'ksamples__resnet_e95_SBI_100ksim_TintLkIRLg.csv')   #waiting for this to be saved 
    ss.append(s.values)
    ln = pd.read_csv('/home/mvasist/samples/1/'+ i +'klnprob__resnet_e95_SBI_100ksim_TintLkIRLg.csv')   #waiting for this to be saved 
    lp.append(ln.values)

sss= np.vstack(ss)
samples = pd.DataFrame(sss)
lll= np.vstack(lp)
log_probability = pd.DataFrame(lll)

In [4]:
samples

             0          1         2         3
0          1.0  656.45703 -1.478516  2.350233
1          2.0  659.59235 -1.508702  2.335082
2          3.0  659.48580 -1.464517  2.405787
3          4.0  659.58060 -1.490735  2.279750
4          5.0  664.84454 -1.523047  2.450851
...        ...        ...       ...       ...
99994  99995.0  822.53845 -2.404268  2.543493
99995  99996.0  816.94525 -2.354554  2.605238
99996  99997.0  824.91345 -2.410438  2.640755
99997  99998.0  834.84340 -2.455547  2.600224
99998  99999.0  824.76370 -2.398262  2.707929

[99999 rows x 4 columns]

In [5]:
log_probability

             0         1
0          1.0 -1.294897
1          2.0 -1.883967
2          3.0 -1.693084
3          4.0 -1.669467
4          5.0 -2.417622
...        ...       ...
99994  99995.0 -2.064807
99995  99996.0 -0.578377
99996  99997.0 -0.973761
99997  99998.0 -0.971395
99998  99999.0 -1.950781

[99999 rows x 2 columns]

In [6]:
log_probability.iloc[:,[1]]

              1
0     -1.294897
1     -1.883967
2     -1.693084
3     -1.669467
4     -2.417622
...         ...
99994 -2.064807
99995 -0.578377
99996 -0.973761
99997 -0.971395
99998 -1.950781

[99999 rows x 1 columns]

In [21]:
fpr, tpr, _= roc_curve(samples.iloc[:,[1,2,3]], log_probability.iloc[:,[1]])

ValueError: continuous-multioutput format is not supported